### ISSUE TITLE
WebDAV 报错导致内核崩溃

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#153]
```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 1177 [running]:
runtime.throw(0x10de6e8, 0x15)
	D:/go1.14/src/runtime/panic.go:1112 +0x79 fp=0xc00052f860 sp=0xc00052f830 pc=0x437f39
runtime.mapassign_faststr(0x1001e00, 0xc0004d0870, 0x10c1506, 0xd, 0x2c)
	D:/go1.14/src/runtime/map_faststr.go:291 +0x3e5 fp=0xc00052f8c8 sp=0xc00052f860 pc=0x4140a5
net/textproto.MIMEHeader.Set(...)
	D:/go1.14/src/net/textproto/header.go:22
net/http.Header.Set(...)
	D:/go1.14/src/net/http/header.go:37
github.com/88250/gowebdav.(*BasicAuth).Authorize(0xc0005109e0, 0xc0004d0900, 0x10a0244, 0x8, 0xc001633580, 0x31)
	D:/gogogo/pkg/mod/github.com/88250/gowebdav@v1.0.0/basicauth.go:32 +0x1d7 fp=0xc00052f990 sp=0xc00052f8c8 pc=0xdd12b7
github.com/88250/gowebdav.(*Client).req(0xc0004d0900, 0x10a0244, 0x8, 0xc001633580, 0x31, 0x12a6220, 0xc00181f320, 0xc00052fbb8, 0x465ea0, 0xc000605e00, ...)
	D:/gogogo/pkg/mod/github.com/88250/gowebdav@v1.0.0/requests.go:28 +0x28a fp=0xc00052fb58 sp=0xc00052f990 pc=0xdd5a0a
github.com/88250/gowebdav.(*Client).propfind(0xc0004d0900, 0xc001633580, 0x31, 0x1ae0a00, 0x1118514, 0xcb, 0xf01920, 0xc0005c8750, 0xc00052fcc8, 0x0, ...)
	D:/gogogo/pkg/mod/github.com/88250/gowebdav@v1.0.0/requests.go:93 +0x11b fp=0xc00052fc20 sp=0xc00052fb58 pc=0xdd6bfb
github.com/88250/gowebdav.(*Client).ReadDir(0xc0004d0900, 0xc001633580, 0x31, 0xc000504a80, 0xc001380000, 0x80000, 0x80000, 0x0)
	D:/gogogo/pkg/mod/github.com/88250/gowebdav@v1.0.0/client.go:165 +0x1ad fp=0xc00052fd00 sp=0xc00052fc20 pc=0xdd1abd
github.com/siyuan-note/siyuan-src/kernel/model.(*Box).Ls(0xc0000d4720, 0xc001633580, 0x31, 0xc0000d4720, 0x8, 0xc00052fd18, 0x723b12, 0x0)
	D:/88250/siyuan-src/kernel/model/conf.go:426 +0x65 fp=0xc00052fdb8 sp=0xc00052fd00 pc=0xe76f15
github.com/siyuan-note/siyuan-src/kernel/model.Ls(0xc001927740, 0x1f, 0xc001633580, 0x31, 0xc001934998, 0x405285, 0xc000e13ec0, 0xc00052ffc0, 0xc000504a01)
	D:/88250/siyuan-src/kernel/model/file.go:99 +0x94 fp=0xc00052ff00 sp=0xc00052fdb8 pc=0xe7bdb4
github.com/siyuan-note/siyuan-src/kernel/cmd.(*ls).Exec(0xc000996200)
	D:/88250/siyuan-src/kernel/cmd/ls.go:21 +0x12f fp=0xc00052ffa8 sp=0xc00052ff00 pc=0xe9ff0f
github.com/siyuan-note/siyuan-src/kernel/cmd.Exec.func1(0x12b80a0, 0xc000996200)
	D:/88250/siyuan-src/kernel/cmd/cmd.go:138 +0x5a fp=0xc00052ffd0 sp=0xc00052ffa8 pc=0xea45da
runtime.goexit()
	D:/go1.14/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00052ffd8 sp=0xc00052ffd0 pc=0x469001
created by github.com/siyuan-note/siyuan-src/kernel/cmd.Exec
	D:/88250/siyuan-src/kernel/cmd/cmd.go:136 +0x50
```

```
列出笔记本 [https://dav.jianguoyun.com/dav/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
```

**Comment by LeoXing1996** [comment]
0.6.3版本使用WebDAV同步坚果云出现了类似的错误, 请问该如何处理呢?

![image](https://user-images.githubusercontent.com/28132635/105001826-52acf800-5a6b-11eb-9d7f-7a4462ff6c36.png)

**Comment by 88250** [comment]
@LeoXing1996 你好，这个文件夹下面大概有多少文件（包括所有资源文件 ）？

**Comment by LeoXing1996** [comment]
是空的，刚刚在MAC下测试没有问题，但是下午在win10系统上会发生这个报错

**Comment by 88250** [comment]
请参考下这里：

![image](https://user-images.githubusercontent.com/873584/105055812-6fb6ea80-5aae-11eb-9622-ef77a10ffeed.png)

如果现在已经加了文件夹路径，那可能是服务端配额限制了。
