### ISSUE TITLE
端口问题

### ISSUE THREAD

**Issue by RealKiro** [siyuan-note/siyuan#3957]
### 描述问题 Describe the problem
![image](https://user-images.githubusercontent.com/33367701/151668562-bfe19fa1-b6b2-48ce-a0b2-04e7e8795b30.png)

群晖使用host模式，通过路由器公网Openwrt的Frps-Frpc反向代理，将Docker思源笔记的`6806`端口重定向给[note.13145212.xyz](http://note.13145212.xyz)并已配置servePath="note.13145212.xyz"，但仍无法进入笔记编辑界面

控制台：
```markdown
main.c8a1c2ccc76536a33c13.js:1 GET http://note.13145212.xyz:6806/stage/protyle/js/pdf/pdf.js?v=2.12.0 net::ERR_CONNECTION_REFUSED
t.addScriptSync @ main.c8a1c2ccc76536a33c13.js:1
9492 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
8884 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
4862 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
5151 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
7683 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
8888 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
4868 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
8890 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
5841 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
4256 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
7396 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
7813 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
5933 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
1787 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
4853 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
4976 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
5322 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
16 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
3725 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
5148 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
4529 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
2936 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
8887 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
618 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
4489 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
6154 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
8842 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
5960 @ main.c8a1c2ccc76536a33c13.js:1
n @ main.c8a1c2ccc76536a33c13.js:1
(anonymous) @ main.c8a1c2ccc76536a33c13.js:1
(anonymous) @ main.c8a1c2ccc76536a33c13.js:1
(anonymous) @ main.c8a1c2ccc76536a33c13.js:1
Show 30 more frames
main.c8a1c2ccc76536a33c13.js:1 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://note.13145212.xyz:6806/stage/protyle/js/pdf/pdf.js?v=2.12.0'.
    at t.addScriptSync (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:964911)
    at Object.9492 (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:322017)
    at n (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:1215252)
    at Module.8884 (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:34240)
    at n (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:1215252)
    at Module.4862 (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:322263)
    at n (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:1215252)
    at Object.5151 (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:358752)
    at n (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:1215252)
    at Object.7683 (http://note.13145212.xyz/stage/build/desktop/main.c8a1c2ccc76536a33c13.js:1:568150)
```

### 期待的结果 Expected result

修复方案

### 版本环境 Version environment

* Version: v1.4.4(kernel:1.7.9)
* Operating system: amd64 Docker-compose
* Browser (if used): Chrome

### 日志文件 Log File
```markdown


date | stream | content
-- | -- | --
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 serve.go:68: kernel is booting [http://0.0.0.0:6806]
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 working.go:133: kernel booted
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 conf.go:499: post-init database size [33 kB], tree stat [count=0, size=0 B]
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 index.go:354: resolved refs [0]
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 index.go:214: resolving refs...
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 conf.go:478: pre-init database size [33 kB]
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 conf.go:263: local serve path [http://note.13145212.xyz]
2022-01-29 16:31:57 | stdout | * workspace directory [/home/siyuan/Documents/SiYuan, data 20 kB]
2022-01-29 16:31:57 | stdout | * database [ver=20211218]
2022-01-29 16:31:57 | stdout | * container [docker]
2022-01-29 16:31:57 | stdout | * read only [false]
2022-01-29 16:31:57 | stdout | * working directory [/opt/siyuan]
2022-01-29 16:31:57 | stdout | * runtime mode [prod]
2022-01-29 16:31:57 | stdout | * arch [amd64]
2022-01-29 16:31:57 | stdout | * ver [1.7.9]
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 runtime.go:32: kernel is booting:
2022-01-29 16:31:57 | stdout | \__\/                                 \__\/         \__\/         \__\/
2022-01-29 16:31:57 | stdout | /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
2022-01-29 16:31:57 | stdout | \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
2022-01-29 16:31:57 | stdout | \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
2022-01-29 16:31:57 | stdout | \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
2022-01-29 16:31:57 | stdout | /__/:/ /:/\:\ \__\/\:\__   __\|__\|:\|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
2022-01-29 16:31:57 | stdout | /  /:/ /::\  /__/::\        \|  \|:\|    ___  \  \:\   /  /:/~/::\   _____\__\:\
2022-01-29 16:31:57 | stdout | /  /:/ /\    /  /:/        \|  \|:\|        \  \:\     /  /:/\:\        \  \:\
2022-01-29 16:31:57 | stdout | /  /:/_      /  /\         /__/\|       \  \:\       /  /::\        \  \:\
2022-01-29 16:31:57 | stdout | /  /\        ___           ___        /__/\         /  /\         /__/\
2022-01-29 16:31:57 | stdout | ___                                   ___           ___           ___
2022-01-29 16:31:57 | stdout | I 2022/01/30 00:31:57 working.go:93:
2022-01-29 16:30:35 | stdout | I 2022/01/30 00:30:35 conf.go:354: exited kernel
2022-01-29 16:30:35 | stdout | I 2022/01/30 00:30:35 process.go:36: received os signal [terminated], exit kernel process now
2022-01-29 16:30:16 | stdout | I 2022/01/30 00:30:16 working.go:133: kernel booted
2022-01-29 16:30:16 | stdout | I 2022/01/30 00:30:16 conf.go:499: post-init database size [33 kB], tree stat [count=0, size=0 B]
2022-01-29 16:30:16 | stdout | I 2022/01/30 00:30:16 index.go:354: resolved refs [0]
2022-01-29 16:30:16 | stdout | I 2022/01/30 00:30:16 index.go:214: resolving refs...
2022-01-29 16:30:16 | stdout | I 2022/01/30 00:30:16 conf.go:478: pre-init database size [33 kB]
2022-01-29 16:30:16 | stdout | I 2022/01/30 00:30:16 serve.go:68: kernel is booting [http://0.0.0.0:6806]
2022-01-29 16:30:15 | stdout | I 2022/01/30 00:30:15 conf.go:263: local serve path [http://note.13145212.xyz]
2022-01-29 16:30:15 | stdout | * workspace directory [/home/siyuan/Documents/SiYuan, data 20 kB]
2022-01-29 16:30:15 | stdout | * database [ver=20211218]
2022-01-29 16:30:15 | stdout | * container [docker]
2022-01-29 16:30:15 | stdout | * read only [false]
2022-01-29 16:30:15 | stdout | * working directory [/opt/siyuan]
2022-01-29 16:30:15 | stdout | * runtime mode [prod]
2022-01-29 16:30:15 | stdout | * arch [amd64]
2022-01-29 16:30:15 | stdout | * ver [1.7.9]
2022-01-29 16:30:15 | stdout | I 2022/01/30 00:30:15 runtime.go:32: kernel is booting:
2022-01-29 16:30:15 | stdout | \__\/                                 \__\/         \__\/         \__\/
2022-01-29 16:30:15 | stdout | /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
2022-01-29 16:30:15 | stdout | \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
2022-01-29 16:30:15 | stdout | \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
2022-01-29 16:30:15 | stdout | \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
2022-01-29 16:30:15 | stdout | /__/:/ /:/\:\ \__\/\:\__   __\|__\|:\|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
2022-01-29 16:30:15 | stdout | /  /:/ /::\  /__/::\        \|  \|:\|    ___  \  \:\   /  /:/~/::\   _____\__\:\
2022-01-29 16:30:15 | stdout | /  /:/ /\    /  /:/        \|  \|:\|        \  \:\     /  /:/\:\        \  \:\
2022-01-29 16:30:15 | stdout | /  /:/_      /  /\         /__/\|       \  \:\       /  /::\        \  \:\
2022-01-29 16:30:15 | stdout | /  /\        ___           ___        /__/\         /  /\         /__/\
2022-01-29 16:30:15 | stdout | ___                                   ___           ___           ___
2022-01-29 16:30:15 | stdout | I 2022/01/30 00:30:15 working.go:93:


```
### 更多信息 More information
- 我的反代方案为：
    - 家庭公网`FRPS`+`FRPC`
- 我的设备环境为：
    - OpenWrt路由器+群晖
- 我的端口环境为：
    - 群晖：`host `（`6806`）
    - 路由FRPC：`群晖ip:6806` --> `note.13145212.xyz`

**Comment by RealKiro** [comment]
> 需要消除 6806 端口的话需要在宿主机上将 Docker 容器 6806 映射到任意一个端口（比如 16806），然后宿主机上用 80/443 反代这个端口。

在将端口改为其他如`6808`后这个问题已解决，感谢🙏
