### ISSUE TITLE
导入 Markdown 文件内核连接中断

### ISSUE THREAD

**Issue by helloxz** [siyuan-note/siyuan#4241]
### 描述问题 Describe the problem

* 操作系统：Windows 10
* 问题现象：通过Markdown文件夹导入到思源笔记，索引完64篇文档后必定奔溃。（内核连接中断）反复尝试依然如此，尝试过减少文档数量也是如此，是不是导入的文件夹不能大于64个文档呀？

![](https://img.rss.ink/imgs/2022/03/2021e179a9d215ed.png)

### 期待的结果 Expected result

通过导入Markdown文件夹导入到思源笔记能正常使用。

### 日志文件 Log File

```
I 2022/03/14 20:06:01 runtime.go:32: kernel is booting:
    * ver [1.8.9]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20211218]
    * workspace directory [C:\Users\xiaoz\Documents\SiYuan, data 8.2 MB]
I 2022/03/14 20:06:01 conf.go:263: local serve path [http://192.168.50.32:6806]
I 2022/03/14 20:06:01 serve.go:68: kernel is booting [http://127.0.0.1:6806]
I 2022/03/14 20:06:01 conf.go:479: pre-init database size [1.0 MB]
I 2022/03/14 20:06:01 index.go:132: use existing database for box [20220314193306-ws1vlta]
I 2022/03/14 20:06:01 index.go:214: resolving refs...
I 2022/03/14 20:06:01 index.go:354: resolved refs [0]
I 2022/03/14 20:06:01 conf.go:500: post-init database size [1.0 MB], tree stat [count=470, size=3.8 MB]
I 2022/03/14 20:06:01 working.go:133: kernel booted
I 2022/03/14 20:06:29 database.go:72: reinitialized database [C:\Users\xiaoz\Documents\SiYuan\temp\siyuan.db]
I 2022/03/14 20:06:29 index.go:204: rebuilt database for notebook [20220314193306-ws1vlta] in [0.00s], tree stat [count=10, size=22 kB]
I 2022/03/14 20:06:29 index.go:214: resolving refs...
I 2022/03/14 20:06:29 index.go:354: resolved refs [0]
I 2022/03/14 20:07:14 database.go:72: reinitialized database [C:\Users\xiaoz\Documents\SiYuan\temp\siyuan.db]
I 2022/03/14 20:07:14 index.go:204: rebuilt database for notebook [20220314193306-ws1vlta] in [0.01s], tree stat [count=13, size=43 kB]
I 2022/03/14 20:07:14 index.go:214: resolving refs...
I 2022/03/14 20:07:14 index.go:354: resolved refs [0]
I 2022/03/14 20:08:01 database.go:72: reinitialized database [C:\Users\xiaoz\Documents\SiYuan\temp\siyuan.db]
F 2022/03/14 20:08:02 node.go:30: format node [20220314200800-x486jb7] in tree [20220314200800-vo4k2a9] failed: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	goroutine 362 [running]:
runtime/debug.Stack()
	D:/go1.17/src/runtime/debug/stack.go:24 +0x65
github.com/88250/lute/util.RecoverPanic(0xc000f45438)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/util/panic.go:23 +0x5b
panic({0x1bd08c0, 0x1ab81c0})
	D:/go1.17/src/runtime/panic.go:1038 +0x215
github.com/88250/lute/render.(*FormatRenderer).renderTable(0xc0002f2d40, 0xc000a81d40, 0x6f)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/render/format_renderer.go:808 +0x156
github.com/88250/lute.FormatNodeSync.func1(0xc000a81d40, 0x20)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/lute.go:243 +0x189
github.com/88250/lute/ast.walk(0xc000a81d40, 0xc000f45448)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/ast/walk.go:36 +0x2f
github.com/88250/lute/ast.Walk(...)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/ast/walk.go:31
github.com/88250/lute.FormatNodeSync(0x0, 0xc00053aa00, 0xc000146dc0)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/lute.go:237 +0x265
github.com/siyuan-note/siyuan-src/kernel/treenode.FormatNode(0xc000a81d40, 0x1)
	D:/88250/siyuan-src/kernel/treenode/node.go:27 +0x45
github.com/siyuan-note/siyuan-src/kernel/treenode.NodeHash(0xc000a81d40, 0xc000df0160, 0x1f)
	D:/88250/siyuan-src/kernel/treenode/tree.go:32 +0x125
github.com/siyuan-note/siyuan-src/kernel/sql.buildBlockFromNode(0xc000a81d40, 0xc000df0160)
	D:/88250/siyuan-src/kernel/sql/database.go:612 +0x172
github.com/siyuan-note/siyuan-src/kernel/sql.fromTree.func1(0xc000a81d40, 0xf0)
	D:/88250/siyuan-src/kernel/sql/database.go:372 +0x86c
github.com/88250/lute/ast.walk(0xc000a81d40, 0xc000f45cf0)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/ast/walk.go:36 +0x2f
github.com/88250/lute/ast.walk(0xc0005ba6c0, 0xc000f45cf0)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/ast/walk.go:44 +0x91
github.com/88250/lute/ast.Walk(...)
	D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.4-0.20220307153455-d8ec991996c4/ast/walk.go:31
github.com/siyuan-note/siyuan-src/kernel/sql.fromTree(0x24, 0x1f6fff0)
	D:/88250/siyuan-src/kernel/sql/database.go:338 +0x117
github.com/siyuan-note/siyuan-src/kernel/sql.insertBlocksSpans(0x1f6fff0, 0xc000032180)
	D:/88250/siyuan-src/kernel/sql/upsert.go:360 +0x39
github.com/siyuan-note/siyuan-src/kernel/sql.InsertBlocksSpans(0xc00060eeb0, 0xc000df0160)
	D:/88250/siyuan-src/kernel/sql/upsert.go:27 +0x25
github.com/siyuan-note/siyuan-src/kernel/model.(*Box).Index.func3({0x1b62ee0, 0xc00053d3b0})
	D:/88250/siyuan-src/kernel/model/index.go:180 +0x225
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1()
	D:/gogogo/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker_func.go:70 +0xa2
created by github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run
	D:/gogogo/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker_func.go:48 +0x68
```

**Comment by 88250** [comment]
应该是遇到了一个解析错误，如果方便的话请把导入的 Markdown 打包发给我们 845765@qq.com

**Comment by 88250** [comment]
非常感谢帮助，已经确认问题，将在下个版本进行修复。
