### ISSUE TITLE
偶发的启动白屏问题

### ISSUE THREAD

**Issue by anmol26s** [siyuan-note/siyuan#438]
Hi
I have an error in version 0.4 and above. I get white screen with this error in command line.

`(siyuan:10262): Gtk-WARNING **: 20:22:33.045: Theme parsing error: gtk.css:3691:13: Not using units is deprecated. Assuming 'px'.`
I am using KDE desktop.

**Comment by 88250** [comment]
Hi, if you have used v0.3.0 and before, please remove ~/.siyuan/ manually and then restart SiYuan.

**Comment by anmol26s** [comment]
I removed the ~/.siyuan/manually and then tried 0.4.1 again. It shows this now.

```
(siyuan:16072): Gtk-WARNING **: 20:35:55.892: Theme parsing error: gtk.css:3691:13: Not using units is deprecated. Assuming 'px'.
(node:16072) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/****/.siyuan/windowState.json'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1283:35)
    at createWindow (/home/****/Downloads/siyuan-0.4.1-linux/resources/app.asar/electron/main.js:26:8)
    at /home/****/Downloads/siyuan-0.4.1-linux/resources/app.asar/electron/main.js:285:3
(node:16072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Vanessa219** [comment]
pls try again:
1. uninstall siyuan
2. remove  ~/.siyuan 
3. download 0.4.2 and install

**Comment by anmol26s** [comment]
Removed ~/.siyuan and tried the version 0.4.2 but it has same error and white screen. Version 0.3.8 works for me.

**Comment by Vanessa219** [comment]
Create the file '/home/****/.siyuan/windowState.json' with the following content:
```
{}
```

Then try again.

We will fix it in the next version.
