### ISSUE TITLE
Docker部署服务端后, pdf.js加载路径硬编码导致的反向代理失败

### ISSUE THREAD

**Issue by charlieJ107** [siyuan-note/siyuan#4459]
### 描述问题 Describe the problem
**现象**: 使用nginx对siyuan进行反向代理, 并配置SSL后, 打开页面时卡在Logo页面无法进入
**(可能的)原因:** 
1. 先决条件(nginx与SSL配置)
    * 配置域名mydomain.com到服务器的https访问至nginx
    * 配置了http访问到mydomain.com时自动重定向到https
    * nginx将访问到mydomain.com:443的请求反向代理到siyuan的docker容器的6806端口
    * 配置siyuan的docker容器启动参数: ` docker run --name siyuan -d -p 6806:6806 b3log/siyuan -servePath mydomain.com:443 -ssl`

2. 问题发生的过程: 
    * 进入主页面时, 前端向后端请求加载pdf.js的路径未受到servePath和ssl两个参数的影响, 在硬编码下继续访问`http://"window.location.hostname+\":6806\""`请求各项资源, 在此场景下, 请求的url为`http://mydomain.com:6806/xxx`
    * 由于nginx会将所有访问至mydomain.com的请求全部重定向为https协议, 则经过重定向后的路径为`https://mydomain.com:6806`
    * 但由于6806暴露的是siyuan kernel, 使用的是http协议进行响应, 因此请求失败
**复现方法:**
1. 先决条件:
    * 准备域名mydomain.com
    * 安装好docker
2. 为了快速获得一个符合复现场景的https与nginx配置, 可以使用[nginx-proxy/acme-companion](https://github.com/nginx-proxy/acme-companion)
```bash
# 配置nginx-proxy
$ curl https://raw.githubusercontent.com/nginx-proxy/nginx-proxy/main/nginx.tmpl > /path/to/nginx.tmpl
$ docker run --detach \
    --name nginx-proxy \
    --publish 80:80 \
    --publish 443:443 \
    --volume conf:/etc/nginx/conf.d  \
    --volume vhost:/etc/nginx/vhost.d \
    --volume html:/usr/share/nginx/html \
    --volume certs:/etc/nginx/certs \
    nginx
$ docker run --detach \
    --name nginx-proxy-gen \
    --volumes-from nginx-proxy \
    --volume /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
    --volume /var/run/docker.sock:/tmp/docker.sock:ro \
    nginxproxy/docker-gen \
    -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
$ docker run --detach \
    --name nginx-proxy-acme \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    --volume acme:/etc/acme.sh \
    --env "NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen" \
    --env "DEFAULT_EMAIL=mail@yourdomain.tld" \
    nginxproxy/acme-companion

# 运行siyuan容器
docker run --name siyuan -d --restart always \
-v $(pwd)/SiYuan:/root/Documents/SiYuan  \
-e VIRTUAL_HOST="mydomain.com" \
-e LETSENCRYPT_HOST="mydomain.com"  \
-e VIRTUAL_PORT=6806 \ # VIRTUAL_PORT环境变量将保证nginx-proxy将xiyuan容器:6806 代理至 mydomain.com:443
-p 6806:6806 \
b3log/siyuan -servePath mydomain.com:443 -ssl

```
此时访问`https://mydomain.com`, 将卡在logo页面. (如果使用了authCode, 将在输入密码后卡在logo页面)
打开控制台, 会发现如下报错信息: 
```
main.17c4dfeefbe6ccce9621.js:1 
        
       Mixed Content: The page at 'https://mydomain.com/stage/build/desktop/?r=zdbp0qr' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mydomain.com:6806/stage/protyle/js/pdf/pdf.js?v=2.14.102'. This request has been blocked; the content must be served over HTTPS.

main.17c4dfeefbe6ccce9621.js:1 
        
       Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://mydomain.com:6806/stage/protyle/js/pdf/pdf.js?v=2.14.102'.
    at t.addScriptSync (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:1024133)
    at Object.9492 (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:363249)
    at n (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:1304854)
    at Module.5142 (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:36003)
    at n (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:1304854)
    at Module.4862 (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:363497)
    at n (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:1304854)
    at Object.5151 (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:400113)
    at n (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:1304854)
    at Object.7683 (https://mydomain.com/stage/build/desktop/main.17c4dfeefbe6ccce9621.js:1:610718)
```

### 期待的结果 Expected result
当服务端配置servePath之后, 应当将所有资源请求导向servePath, 同时servePath应考虑协议和SSL支持. 或使用额外的参数对资源请求和访问url进行控制, 确保反向代理能够对所有请求生效. 

### 截屏或者录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/42380833/161223425-d1c46d20-6336-473a-b496-fd6b63c5d5ca.png)

### 版本环境 Version environment

* Version: docker 1.9.6
* Operating system: Ubuntu 20.04 amd64
* Browser (if used): Edge 版本 99.0.1150.55 (正式版本) (64 位)

### 日志文件 Log file
```
I 2022/04/01 15:18:20 working.go:92: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/04/01 15:18:20 runtime.go:32: kernel is booting:
    * ver [1.9.6]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20211218]
    * workspace directory [/home/siyuan/Documents/SiYuan, data 20 kB]
D 2022/04/01 15:18:20 conf.go:112: check device locale failed [detect: not detected], using default language [en_US]
I 2022/04/01 15:18:20 conf.go:263: local serve path [http://127.0.0.1:6806]
I 2022/04/01 15:18:20 serve.go:69: kernel is booting [http://0.0.0.0:6806]
I 2022/04/01 15:18:21 database.go:72: reinitialized database [/home/siyuan/Documents/SiYuan/temp/siyuan.db]
I 2022/04/01 15:18:21 conf.go:488: pre-init database size [4.1 kB]
I 2022/04/01 15:18:21 index.go:189: resolving refs...
I 2022/04/01 15:18:21 index.go:316: resolved refs [0]
I 2022/04/01 15:18:21 conf.go:512: post-init database size [4.1 kB], tree stat [count=0, size=0 B]
I 2022/04/01 15:18:21 working.go:132: kernel booted
```

**Comment by 88250** [comment]
请试一下不使用 ssl 时是否正确。

**Comment by charlieJ107** [comment]
> 请试一下不使用 ssl 时是否正确。

经过测试, 不使用-ssl启动参数时问题依然存在, 现象一致.

**Comment by 88250** [comment]
感觉是参数没传入，试试 `--servePath=yourdomain:443 --ssl=true`。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/4463 中会检查 `--servePath` 参数传入。目前感觉多半是这个原因，但是也不能排除其他原因，麻烦再多帮忙测试看看，谢谢。

**Comment by charlieJ107** [comment]
经过测试, 确认

> 感觉是参数没传入，试试 `--servePath=yourdomain:443 --ssl=true`。

这个方法可以work.

此时, 所有的请求经由nginx监听的80和443端口代理至6806端口. 创建容器时不再需要使用`-p 6806:6806`向外暴露kernel监听的端口. 

## 总结
docker部署siyuan时, 如果需要配置反向代理, 务必需要配置servePath等参数. 此时注意参数应当使用`-arg=value`的方式传入, 否则可能导致参数传入不正确. 例如:
```
--servePath=yourdomain:443 --ssl=true
```
这将避免参数传入失败的问题. 

另, 值得mark一下的是, 初始化时如果没有为容器提供Locale相关环境变量, siyuan kernel会以默认en_US的locale提供英文界面. 这一配置似乎无法在网页端修改(至少我还没有在设置中找到?). 目前来说, 可以通过在创建容器时提供相关环境变量来解决这个问题. 
```bash
docker run --name siyuan -d --restart always \
-v $(pwd)/SiYuan:/home/siyuan/Documents/SiYuan \
-e  LANG=zh_CN.utf-8 \
-e LANGUAGE=zh_CN.utf8 \
-e LC_ALL=zh_CN.utf-8 \
b3log/siyuan \
-servePath=yourdomain:443 \
-ssl=true \
-accessAuthCode="your access Auth Code"
```

非常感谢两位主要开发者的关注与不懈努力. 这个Issue已经被解决, 我将Close这个 issue. 如果有任何问题, 欢迎随时继续讨论.

**Comment by ChinaToby** [comment]
部署在群晖docker里面
我没有使用ssl，用的是6086端口，从1.9.3直接升级到1.9.7 的时候，日志里面也卡在了 这个 错误上
can't work without set --servePath when deploying by docker
（不怎么玩儿Github，不知道什么规矩，大佬们见谅）

**Comment by 88250** [comment]
@ChinaToby 需要增加内核启动参数 `--servePath`

**Comment by mogud** [comment]
极空间 docker
