### ISSUE TITLE
在空白段落块/标题块/单元格中无法使用快捷键 `Ctrl + M` 插入行内公式

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6026]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在空白段落块/标题块/单元格中无法使用快捷键 `Ctrl + M` 插入行内公式
在有任意字符的段落块/标题块/单元格中使用快捷键 `Ctrl + M` 插入行内公式是正常的

### 期待的结果 Expected result

在空白段落块/标题块/单元格中使用快捷键 `Ctrl + M` 插入行内公式

### 版本环境 Version environment

```markdown
- Version: 2.2.3
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

```log
main.5de28c61eef465cc7b73.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'previousSibling')
    at t.hasPreviousSibling (main.5de28c61eef465cc7b73.js:1:896940)
    at l.<anonymous> (main.5de28c61eef465cc7b73.js:1:745948)
    at Generator.next (<anonymous>)
    at main.5de28c61eef465cc7b73.js:1:745411
    at new Promise (<anonymous>)
    at i (main.5de28c61eef465cc7b73.js:1:745156)
    at HTMLButtonElement.<anonymous> (main.5de28c61eef465cc7b73.js:1:745627)
    at main.5de28c61eef465cc7b73.js:1:976398
    at Array.find (<anonymous>)
    at HTMLDivElement.<anonymous> (main.5de28c61eef465cc7b73.js:1:976159)
t.hasPreviousSibling @ main.5de28c61eef465cc7b73.js:1
(anonymous) @ main.5de28c61eef465cc7b73.js:1
(anonymous) @ main.5de28c61eef465cc7b73.js:1
i @ main.5de28c61eef465cc7b73.js:1
(anonymous) @ main.5de28c61eef465cc7b73.js:1
(anonymous) @ main.5de28c61eef465cc7b73.js:1
(anonymous) @ main.5de28c61eef465cc7b73.js:1

```

**Comment by Vanessa219** [comment]
好像都没有办法重现
https://user-images.githubusercontent.com/970828/193280432-64e4a7f1-7d7a-489d-a9da-d81f2d9dd8fe.mp4

**Comment by Vanessa219** [comment]
可能是修改了其他 bug 就好了，还麻烦下个版本再看看。
